### ISSUE TITLE
Nightly builds???

### ISSUE THREAD

**Issue by SANSYBOY1234** [pencil2d/pencil#582]
so the nightly builds arnt really nightly their like monthly builds.... so i was just asking if you guys could actually make them NIGHTLY

**Comment by Jose-Moreno** [comment]
@SANSYBOY1234 You have to realize this is basically a volunteer project, not a commercial product. There are limited human resources and basically only the Lead developer is coding and creating these builds for both Windows and MAC when he is able to. This is a time consuming process, so it's not like he can churn out daily builds after changing three lines of code. 

However should you or anyone have the latest QT development framework and know their way around C++ they should be more than capable to build and run any latest version without worry, in fact we do need any amount of help we can get, because there are actually more people asking for changes than offering help, so if you know someone who can help let them know.

**Comment by J5lx** [comment]
Maybe it would be possible to use a CI service to provide actual nightly builds. It seems that Travis is already building Pencil for Linux on every commit, so all that's left is adding builds for other operating systems and another build step for uploading them somewhere. I'm not all that familiar with packaging standalone applications, but I think it shouldn’t be too difficult to do.

**Comment by J5lx** [comment]
After having a look at the documentation of Travis it seems that they only support Linux and Mac/OS X/macOS/whatever it's called right now. So in order to have Windows builds we’d have to cross-compile the whole thing or use another CI service. I believe AppVeyor is somewhat popular for Windows builds, but I never really had a close look at it to this point.
If someone would tell me how the current nightly builds are packaged I might be able to take a look at this myself, though I can’t guarantee for anything since I don’t have a lot of time right now.

**Comment by Jose-Moreno** [comment]
@J5lx Interesting! Thank you for your offer, and don't worry about time, we're all jam packed with jobs and life. Hopefully @chchwy can also look into this to collaborate with you in this matter. Thanks again for your time and wisdom! :smile:

**Comment by CandyFace** [comment]
I have recently setup both AppVeyor and Travis-CI on one of my other projects, I'll look into this and see if I can get it working. Most of the Travis setup is there already, so it should only be a matter of getting it to build and release on github pages.

**Comment by chchwy** [comment]
Yes, we might need a server or cloud space to upload the Travis-CI builds, then we can get the linux version nightly build (which is missing atm)

**Comment by CandyFace** [comment]
Why not just use the github release page, that's what i'm currently doing for my other project. We could just make it draft if you want to control whenever they should be published or release with 0.5.4.x number automatically

**Comment by chchwy** [comment]
Oh, so there is github release page API? I am not good at these things, I would be very appreciate if you can help :P

**Comment by CandyFace** [comment]
Yeah I'm currenty looking into it, it should be as simple as adding a deploy to the script eg.
```

// travis needs to generate a tag for it to work
after_success:
  - echo -e "Starting to tag commit.\n"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG

before_deploy:
  - cd to/my/build/path
  - zip -r "release_file.zip" Release/

deploy:
  provider: releases
  api_key: 
    secure: <insert encrypted security key>
  file: <path/to/file>
  skip_cleanup: true
  draft: false
  on:
    tags: true
    all_branches: true
    repo: Pencil2d/pencil
```

if everything goes well, then I could get this up and running today :)
That is.. if travis ever starts building, so I can test if it works before I PR :P
